job('First-Maven-Project-Via-DSL'){
    description("First maven project generated by the DSL on ${new Date()} , the project is a small Maven project hosted on github")
    scm{
        git("https://github.com/KoHeinCs/MavenJenkin.git",'main')
    }
    triggers{
        scm('* * * * *')
    }
    steps{
        maven('clean package','pom.xml')
    }
    publishers{
        archiveArtifacts '**/*.jar'
    }
}